### ISSUE TITLE
Image registration in Xenium dataset

### ISSUE THREAD

**Issue by xiachenrui** [mahmoodlab/HEST#45]
Hi  all,

Thanks for your great works!

I want to know if H&E images in Xenium has been registered with cells coordinates. Because in the raw experiment they are not registered. 10x Xenium analysis pipeline provides a file (such as [Supplemental: H&E Image Alignment File (CSV)](https://cf.10xgenomics.com/samples/xenium/1.0.1/Xenium_FFPE_Human_Breast_Cancer_Rep1/Xenium_FFPE_Human_Breast_Cancer_Rep1_he_imagealignment.csv) ) for registration. Do you have applied this file to image ?

Any clarification will be helpful !

Best!

**Comment by xiachenrui** [comment]
I have this question because I found that the cell coordinates kept in `adata.obsm['spatial']` can not matched well with cell location segmented via CellViT (kept in  `{name}_cellvit_seg.geojson` file)

**Comment by pauldoucet** [comment]
Hi @xiachenrui,

See Issue #38, we're currently working on providing .h5ad with transcripts pooled per cell. 

adata.obsm['spatial'] in st/*.h5ad **does not contain cell coordinates**. For now, adata.obsm['spatial'] in the provided .h5ad, only indicates the center of pseudo-visium spots for Xenium, which are pooling of transcripts per region of 100um x 100um.

To answer your question, no, we do not apply any transformation to the H\&E image directly as it's too costly. However the pseudo-spots themselves were indeed aligned using an affine alignment file. The CellViT segmentation is also already aligned with the H\&E by design.

Let me know if it's not clear

**Comment by xiachenrui** [comment]
Thanks for your quick reply !

For **Xenium** slices,  I think `adata.obsm['spatial']` is coordinates for cells defined by 10x xenium analysis pipeline. Does these coordinates already aligned with H&E (or CellViT results)?

Best!

**Comment by pauldoucet** [comment]
Sorry, can you clarify which adata you are talking about? Is is the one you obtained from our huggingface page i.e. `st/....h5ad`?

**Comment by guillaumejaume** [comment]
In Xenium, coords provided as part of HEST in `adata.obsm['spatial']` are not cells, but patches, where transcripts have been pooled to emulate a Visium spot. We are in the processing of releasing the H&E-aligned Xenium coords for each cell.

**Comment by xiachenrui** [comment]
> Copied!Quote reply
> Reference in new

Thanks for your clarification and efforts ! I see !

Best!
