### ISSUE TITLE
Missing Data in Xenium "transcripts/" Folder? 

### ISSUE THREAD

**Issue by sky-lzy** [mahmoodlab/HEST#56]
Hi,
I am working with Xenium data from the "transcripts/" folder and have encountered an issue. It seems that many of the entries, like the "TENX122" dataset, are missing key information such as the "cell_id" and "geometry" fields. I've attached images that illustrate these missing data fields.
![temp1](https://github.com/user-attachments/assets/a73a753a-5ea5-436c-a0a4-45a0a28620fe)
![temp2](https://github.com/user-attachments/assets/fdfd8305-1281-45bd-8795-4d0779c79156)

Additionally, I have a question regarding the coordinates in the "transcripts" data. Are these coordinates aligned with the H&E image? When I attempt to plot the shape of the cells based on this data, the geometry seems off. However, using cell segmentation data from "cellvit" appears to give more reasonable results. I am not sure if I made some mistakes here. Thank you!
![temp](https://github.com/user-attachments/assets/a39cea87-c36d-44d5-83e7-ee44b5f0661b)

**Comment by guillaumejaume** [comment]
Hi, 

Some transcripts are indeed not part of a cell. To give you a bit of background, cell attribution works as follows (provided by 10x here: https://www.10xgenomics.com/support/software/xenium-onboard-analysis/latest/algorithms-overview/segmentation):

-1- DAPI staining and segmentation to extract cell nuclei. Strong overlap with CellViT nuclear segmentation, but not one-on-one 
-2- Enlarge each nucleus with a fixed radius around the centroid. Or if available, use some cell membrane marker
-3- Pool all the transcripts which fall in the cell contour together. 

==> because of this process, some transcripts are lost. Also, the cell segmentation by 10x is not optimal. We are exploring other techniques but it remains an open question (e.g., cell segmentation in H&E is much harder than nuclear segmentation)

**Comment by guillaumejaume** [comment]
The transcripts are aligned with the H&E image. The alignment was done using Valis for fine-grained alignment. Alignment provided by 10x Genomics uses a rigid transformation which is suboptimal due to tissue deformation. 

Keep in mind that transcripts can be measured everywhere in the cell, not necessarily in the nucleus, so the result that you showed seems normal.

Let me know if unclear.

**Comment by sky-lzy** [comment]
It is clear and thank you very much for the response!
