### ISSUE TITLE
spot_diameter and spot_size_um  in Xenium data

### ISSUE THREAD

**Issue by Mengflz** [mahmoodlab/HEST#79]
Hi, thank you for your incredible work on the HEST and for sharing your code. I have a few questions about how spot dimensions are defined in Xenium data processing.
I noticed that in [reader.py](https://github.com/mahmoodlab/HEST/blob/main/src/hest/readers.py), the **spot_size_um** is set to 100um. If I understand it correctly, it seems that “pseudo-Visium” spots are generated by pooling transcripts on a 100*100  rectangle. However, in the [article](https://arxiv.org/pdf/2406.16192), it said "we generated “pseudo-Visium” spots by pooling transcripts on 55 × 55-µm patches without spacing". And in the readers, you set **spot_diameter** = 55. 
So, I am a little comfused about what's the relationship between spot_size_um and  spot_diameter. I don't know if I overlooked some important points. And if I want to generate a smaller “pseudo-Visium”, can I just set the **spot_size_um** to a smaller value?
Thank you in advance!

**Comment by milkshake0901** [comment]
Hi, I also have a similar question. I want to have the xenium data loaded without pooling. Is there a way to achieve this?

**Comment by pauldoucet** [comment]
Hi @Mengflz, 

It seems like there is a typo in the latest revision of the paper. The following is correct:
- Xenium transcripts were pooled into squares of 100umx100um to resemble the 100um Visium spot inter-distance. 
- We then extract patches of 224x224 px at 0.5um/px centered around each pooled spot, to match the input size of patch foundation models. Note that because we pool at 100um and extract patches of 112x112um, there is a small overlap between patches.

Feel free to change the pooling size and patching size as needed. Please refer to the following updated tutorial: https://github.com/mahmoodlab/HEST/blob/main/tutorials/2-Interacting-with-HEST-1k.ipynb 

Note that if you choose to pool at 55um and patch at 112um, you will significantly increase the patch overlap.

**Comment by pauldoucet** [comment]
Hi @milkshake0901,

You can load the transcripts without pooling with the following snippet:

```python
for st in iter_hest('hest_data', id_list=['TENX95'], load_transcripts=True,):
    print(st.transcript_df)
```

**Comment by Mengflz** [comment]
Thank you for your reply! It solved my problem well.
